<a href="https://colab.research.google.com/github/Achillean-1/Text-Mining/blob/main/Text_Mining.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('vader_lexicon')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [ ]:
import pandas as pd
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
import string
import re

In [ ]:
data_amazon = pd.read_csv('/content/drive/MyDrive/Dataset/sentiment labelled sentences/amazon_cells_labelled.csv', names=['text','label','1','2','3','4'], delimiter=None)
data_amazon.head()

,text,label,1,2,3,4
0,So there is no way for me to plug it in here i...,0,NaN,NaN,NaN,NaN
1,Good case,Excellent value.,1,NaN,NaN,NaN
2,Great for the jawbone.,1,NaN,NaN,NaN,NaN
3,Tied to charger for conversations lasting more...,0,NaN,NaN,NaN,NaN
4,The mic is great.,1,NaN,NaN,NaN,NaN

In [ ]:
data_imdb = pd.read_csv('/content/drive/MyDrive/Dataset/sentiment labelled sentences/imdb_labelled.csv', names=['text','label','1','2','3','4','5','6'], delimiter=None)
data_imdb.head()

,text,label,1,2,3,4,5,6
0,A very,very,very slow-moving,aimless movie about a distressed,drifting young man.,0,NaN,NaN
1,Not sure who was more lost - the flat characte...,nearly half of whom walked out.,0,NaN,NaN,NaN,NaN,NaN
2,Attempting artiness with black & white and cle...,the movie disappointed - became even more rid...,0,NaN,NaN,NaN,NaN,NaN
3,Very little music or anything to speak of.,0,NaN,NaN,NaN,NaN,NaN,NaN
4,The best scene in the movie was when Gerardo i...,1,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data_yelp = pd.read_csv('/content/drive/MyDrive/Dataset/sentiment labelled sentences/yelp_labelled.csv', names=['text','label','1','2','3','4'], delimiter=None)
data_yelp.head()

                                                text label    1    2    3   4
0                           Wow... Loved this place.     1  NaN  NaN  NaN NaN
1                                 Crust is not good.     0  NaN  NaN  NaN NaN
2          Not tasty and the texture was just nasty.     0  NaN  NaN  NaN NaN
3  Stopped by during the late May bank holiday of...     1  NaN  NaN  NaN NaN
4  The selection on the menu was great and so wer...     1  NaN  NaN  NaN NaN

In [ ]:
combined_data = pd.DataFrame({
    'Amazon': data_amazon.apply(lambda x: ' '.join([str(val) for val in x.dropna()]), axis=1),
    'IMDB': data_imdb.apply(lambda x: ' '.join([str(val) for val in x.dropna()]), axis=1),
    'Yelp': data_yelp.apply(lambda x: ' '.join([str(val) for val in x.dropna()]), axis=1)
})

In [ ]:
combined_data.columns = ['Amazon', 'IMDB', 'Yelp']

In [ ]:
combined_data.head()

,Amazon,IMDB,Yelp
0,So there is no way for me to plug it in here i...,A very very very slow-moving aimless movie ...,Wow... Loved this place. 1
1,Good case Excellent value. 1,Not sure who was more lost - the flat characte...,Crust is not good. 0
2,Great for the jawbone. 1,Attempting artiness with black & white and cle...,Not tasty and the texture was just nasty. 0
3,Tied to charger for conversations lasting more...,Very little music or anything to speak of. 0,Stopped by during the late May bank holiday of...
4,The mic is great. 1,The best scene in the movie was when Gerardo i...,The selection on the menu was great and so wer...

In [ ]:
# Tokenisasi teks
tokenized_data = combined_data.applymap(lambda x: word_tokenize(str(x)))
#print(tokenized_data)
tokenized_data.head()

,Amazon,IMDB,Yelp
0,"[So, there, is, no, way, for, me, to, plug, it...","[A, very, very, very, slow-moving, aimless, mo...","[Wow, ..., Loved, this, place, ., 1]"
1,"[Good, case, Excellent, value, ., 1]","[Not, sure, who, was, more, lost, -, the, flat...","[Crust, is, not, good, ., 0]"
2,"[Great, for, the, jawbone, ., 1]","[Attempting, artiness, with, black, &, white, ...","[Not, tasty, and, the, texture, was, just, nas..."
3,"[Tied, to, charger, for, conversations, lastin...","[Very, little, music, or, anything, to, speak,...","[Stopped, by, during, the, late, May, bank, ho..."
4,"[The, mic, is, great, ., 1]","[The, best, scene, in, the, movie, was, when, ...","[The, selection, on, the, menu, was, great, an..."

In [ ]:
# Menghapus stop words
stop_words = set(stopwords.words('english'))
filtered_data1 = tokenized_data.applymap(lambda x: [word for word in x if word.lower() not in stop_words])
filtered_data1.head()

,Amazon,IMDB,Yelp
0,"[way, plug, US, unless, go, converter, ., 0]","[slow-moving, aimless, movie, distressed, drif...","[Wow, ..., Loved, place, ., 1]"
1,"[Good, case, Excellent, value, ., 1]","[sure, lost, -, flat, characters, audience, ne...","[Crust, good, ., 0]"
2,"[Great, jawbone, ., 1]","[Attempting, artiness, black, &, white, clever...","[tasty, texture, nasty, ., 0]"
3,"[Tied, charger, conversations, lasting, 45, mi...","[little, music, anything, speak, ., 0]","[Stopped, late, May, bank, holiday, Rick, Stev..."
4,"[mic, great, ., 1]","[best, scene, movie, Gerardo, trying, find, so...","[selection, menu, great, prices, ., 1]"

In [ ]:
# Lemmatisasi teks
lemmatizer = WordNetLemmatizer()
preprocessed_data = filtered_data1.applymap(lambda x: [lemmatizer.lemmatize(word) for word in x])
preprocessed_data.head()

,Amazon,IMDB,Yelp
0,"[way, plug, US, unless, go, converter, ., 0]","[slow-moving, aimless, movie, distressed, drif...","[Wow, ..., Loved, place, ., 1]"
1,"[Good, case, Excellent, value, ., 1]","[sure, lost, -, flat, character, audience, nea...","[Crust, good, ., 0]"
2,"[Great, jawbone, ., 1]","[Attempting, artiness, black, &, white, clever...","[tasty, texture, nasty, ., 0]"
3,"[Tied, charger, conversation, lasting, 45, min...","[little, music, anything, speak, ., 0]","[Stopped, late, May, bank, holiday, Rick, Stev..."
4,"[mic, great, ., 1]","[best, scene, movie, Gerardo, trying, find, so...","[selection, menu, great, price, ., 1]"

In [ ]:
# Menghapus tanda baca
punctuation = set(string.punctuation)
filtered_data2 = preprocessed_data.applymap(lambda x: [word for word in x if word not in punctuation and len(word) > 1])
filtered_data2.head()

,Amazon,IMDB,Yelp
0,"[way, plug, US, unless, go, converter]","[slow-moving, aimless, movie, distressed, drif...","[Wow, ..., Loved, place]"
1,"[Good, case, Excellent, value]","[sure, lost, flat, character, audience, nearly...","[Crust, good]"
2,"[Great, jawbone]","[Attempting, artiness, black, white, clever, c...","[tasty, texture, nasty]"
3,"[Tied, charger, conversation, lasting, 45, min...","[little, music, anything, speak]","[Stopped, late, May, bank, holiday, Rick, Stev..."
4,"[mic, great]","[best, scene, movie, Gerardo, trying, find, so...","[selection, menu, great, price]"

In [ ]:
# Menghapus kata yang tidak perlu
unnecessary_words = set(['the', 'a', 'an'])
filtered_data3 = filtered_data2.applymap(lambda x: [word for word in x if word.lower() not in unnecessary_words])
filtered_data3.head()

,Amazon,IMDB,Yelp
0,"[way, plug, US, unless, go, converter]","[slow-moving, aimless, movie, distressed, drif...","[Wow, ..., Loved, place]"
1,"[Good, case, Excellent, value]","[sure, lost, flat, character, audience, nearly...","[Crust, good]"
2,"[Great, jawbone]","[Attempting, artiness, black, white, clever, c...","[tasty, texture, nasty]"
3,"[Tied, charger, conversation, lasting, 45, min...","[little, music, anything, speak]","[Stopped, late, May, bank, holiday, Rick, Stev..."
4,"[mic, great]","[best, scene, movie, Gerardo, trying, find, so...","[selection, menu, great, price]"

In [ ]:
# Menghapus elemen list kosong
filtered_data4 = filtered_data3.applymap(lambda x: list(filter(None, x)))
filtered_data4.head()

,Amazon,IMDB,Yelp
0,"[way, plug, US, unless, go, converter]","[slow-moving, aimless, movie, distressed, drif...","[Wow, ..., Loved, place]"
1,"[Good, case, Excellent, value]","[sure, lost, flat, character, audience, nearly...","[Crust, good]"
2,"[Great, jawbone]","[Attempting, artiness, black, white, clever, c...","[tasty, texture, nasty]"
3,"[Tied, charger, conversation, lasting, 45, min...","[little, music, anything, speak]","[Stopped, late, May, bank, holiday, Rick, Stev..."
4,"[mic, great]","[best, scene, movie, Gerardo, trying, find, so...","[selection, menu, great, price]"

In [ ]:
# Menggabungkan kata-kata menjadi kalimat
processed_sentences = filtered_data4.applymap(lambda x: ' '.join(x))
processed_sentences.head()

,Amazon,IMDB,Yelp
0,way plug US unless go converter,slow-moving aimless movie distressed drifting ...,Wow ... Loved place
1,Good case Excellent value,sure lost flat character audience nearly half ...,Crust good
2,Great jawbone,Attempting artiness black white clever camera ...,tasty texture nasty
3,Tied charger conversation lasting 45 minutes.M...,little music anything speak,Stopped late May bank holiday Rick Steve recom...
4,mic great,best scene movie Gerardo trying find song keep...,selection menu great price

In [ ]:
# Simpan hasil preprocessing ke dalam file CSV baru
processed_sentences.to_csv('/content/drive/MyDrive/Dataset/sentiment labelled sentences/preprocessing_combined_data.csv', index=False)